// generated from glossary.json — do not edit
/** @typedef {'braid'|'fan'} TopRule */
/** @typedef {'lay'|'park'|'resume'|'start-run'|'stitch'} OpKind */
/** @typedef {'corner'|'free'|'rail'|'splice'|'tail'} SegClass */
/** @typedef {'climb'|'contact'|'crossing'|'rail-parallel'|'squeeze'|'tipCross'|'wedge'} CrossKind */

export const TOP_RULES = Object.freeze({
  braid: 'braid',
  fan: 'fan'
});

export const TERM = Object.freeze({
  address: { ru: 'адрес разметки', en: 'address' },
  alternate: { ru: 'чередование', en: 'alternate row order' },
  amime: { ru: 'амимэ', en: 'amime kagari', ja: '網目かがり' },
  anchor: { ru: 'закрепление', en: 'anchor' },
  apex: { ru: 'вершина (перекрёста)', en: 'apex' },
  around: { ru: 'обхват', en: 'around' },
  asanoha: { ru: 'асаноха', en: 'asanoha', ja: '麻の葉' },
  belt: { ru: 'пояс', en: 'belt' },
  bite: { ru: 'укус', en: 'bite' },
  blocks: { ru: 'блоками', en: 'block row order' },
  bow: { ru: 'дуга малого круга', en: 'bow shoulder' },
  bridge: { ru: 'мост', en: 'bridge' },
  C10: { ru: 'C10 (комбинированное деление 10)', en: 'C10 marking' },
  C6: { ru: 'C6 (разметка «6 Combination»)', en: 'C6 marking' },
  C8: { ru: 'C8', en: 'C8 marking' },
  cap: { ru: 'потолок', en: 'cap' },
  channel: { ru: 'канал иглы', en: 'needle channel' },
  chidori: { ru: 'тидори', en: 'chidori', ja: '千鳥かがり' },
  circumference: { ru: 'окружность мари', en: 'circumference', ja: '円周' },
  climb: { ru: 'слив', en: 'climb merge' },
  closingStitch: { ru: 'замыкающий стежок', en: 'closing stitch' },
  cluster: { ru: 'кластер иглы', en: 'cluster' },
  collision: { ru: 'столкновение наборов', en: 'set collision' },
  contact: { ru: 'контакт', en: 'contact' },
  contradiction: { ru: 'противоречие', en: 'contradiction' },
  corner: { ru: 'угловая дуга', en: 'corner arc' },
  crossing: { ru: 'перекрёст', en: 'crossing' },
  crossover: { ru: 'перехлёст', en: 'crossover' },
  dent: { ru: 'вмятина', en: 'dent' },
  drain: { ru: 'слив к отверстию', en: 'drain' },
  edge: { ru: 'вплотную', en: 'edge' },
  eLine: { ru: 'E-линия', en: 'E-line' },
  equator: { ru: 'экватор', en: 'equator', ja: '赤道' },
  fan: { ru: 'веер', en: 'fan' },
  flight: { ru: 'полёт', en: 'flight' },
  free: { ru: 'свободный участок', en: 'free arc class' },
  'free-graze': { ru: 'касание без рельса', en: 'free-graze' },
  geodesic: { ru: 'геодезическая', en: 'geodesic shoulder' },
  groom: { ru: 'пригладить', en: 'groom' },
  halfLine: { ru: 'полулиния', en: 'half-line' },
  hanabira: { ru: 'лепесток', en: 'petal', ja: '花びら' },
  hidden: { ru: 'скрытый проход', en: 'hidden run' },
  holdSet: { ru: 'удержание', en: 'hold set' },
  'hole-entry': { ru: 'вход', en: 'hole entry' },
  'hole-exit': { ru: 'выход', en: 'hole exit' },
  hull: { ru: 'оболочка', en: 'hull' },
  itoDome: { ru: 'ито-домэ', en: 'thread fastening', ja: '糸止め' },
  jimaki: { ru: 'обмотка основы', en: 'jimaki', ja: '地巻き' },
  kagari: { ru: 'кагари', en: 'kagari stitching', ja: 'かがり' },
  kagome: { ru: 'кагомэ', en: 'kagome', ja: '籠目' },
  kamiTape: { ru: 'бумажная лента', en: 'paper strip', ja: '紙テープ' },
  kashin: { ru: 'касин', en: 'flower centre', ja: '花芯' },
  kiku: { ru: 'кику', en: 'kiku', ja: '菊' },
  kink: { ru: 'излом полёта', en: 'kink' },
  kotengiku: { ru: 'котэн-гику', en: 'classic kiku', ja: '古典菊' },
  kousa: { ru: 'коуса', en: 'kousa', ja: '交差かがり' },
  kumiawaseTobun: { ru: 'комбинированное деление', en: 'combination division (C-N)', ja: '組み合わせ等分' },
  landing: { ru: 'посадка', en: 'landing' },
  lattice: { ru: 'решётка', en: 'lattice' },
  lay: { ru: 'уложить плечо', en: 'lay leg' },
  leg: { ru: 'плечо', en: 'leg (shoulder segment)' },
  lift: { ru: 'подъём (нити)', en: 'lift' },
  machibari: { ru: 'булавки-метки', en: 'marking pins', ja: '待ち針' },
  makiKagari: { ru: 'макикагари', en: 'maki kagari', ja: '巻きかがり' },
  mari: { ru: 'основа', en: 'mari ball', ja: '土台まり', ruCanon: 'мари' },
  mariShin: { ru: 'сердцевина', en: 'core', ja: '手まり芯' },
  marking: { ru: 'разметка', en: 'marking lines', ja: '地割り' },
  markingGraph: { ru: 'граф разметки', en: 'marking graph' },
  masu: { ru: 'масу', en: 'masu', ja: '枡かがり' },
  matsuba: { ru: 'мацуба', en: 'matsuba', ja: '松葉かがり' },
  metallic: { ru: 'ламе', en: 'metallic thread', ja: 'ラメ糸' },
  NP: { ru: 'СП', en: 'north pole', ja: '北極', ruCanon: 'северный полюс' },
  obi: { ru: 'оби', en: 'obi', ja: '帯' },
  obiKagari: { ru: 'оби-кагари', en: 'obi kagari', ja: '帯かがり' },
  occupancy: { ru: 'занятость', en: 'occupancy' },
  park: { ru: 'парковка', en: 'park' },
  patch: { ru: 'пятно контакта', en: 'contact patch' },
  perle5: { ru: 'перле №5', en: 'Perle cotton #5', ja: '5番刺繍糸' },
  petalSpan: { ru: 'лепесток через доли', en: 'petal span' },
  pickup: { ru: 'захват', en: 'pickup' },
  plateau: { ru: 'площадка', en: 'plateau' },
  polygon: { ru: 'ряды вокруг грани', en: 'polygon' },
  program: { ru: 'программа', en: 'program' },
  rail: { ru: 'рельс', en: 'rail' },
  'rail-parallel': { ru: 'параллель рельса', en: 'rail parallel' },
  region: { ru: 'область', en: 'region' },
  resume: { ru: 'продолжить', en: 'resume thread' },
  rib: { ru: 'ребро', en: 'rib' },
  root: { ru: 'корень упаковки', en: 'packing root' },
  round: { ru: 'обход', en: 'round', ja: '周' },
  row: { ru: 'ряд', en: 'row', ja: '段' },
  S_N: { ru: 'S_N', en: 'Simple N (S_N)', ruCanon: 'простое деление на N (S_N)' },
  sag: { ru: 'прогиб', en: 'sag' },
  sakasa: { ru: 'sakasa', en: 'sakasa uwagake', ja: '逆さ上掛け', ruCanon: 'сакаса увагакэ' },
  separate: { ru: 'раздвинута', en: 'separate' },
  sequence: { ru: 'явная последовательность', en: 'explicit sequence' },
  set: { ru: 'набор', en: 'thread set' },
  shitagake: { ru: 'shitagake', en: 'shitagake chidori', ja: '下掛け千鳥かがり', ruCanon: 'ситагакэ' },
  skein: { ru: 'моток', en: 'skein', ja: 'かせ' },
  SP: { ru: 'южный полюс', en: 'SP', ja: '南極' },
  splice: { ru: 'стык', en: 'splice' },
  squeeze: { ru: 'тесное место', en: 'squeeze' },
  stack: { ru: 'стопка', en: 'stack' },
  staircase: { ru: 'лесенка', en: 'staircase' },
  'start-run': { ru: 'скрытый старт', en: 'start hidden run' },
  stitch: { ru: 'стежок', en: 'stitch' },
  stitchSpan: { ru: 'пролёт стежка', en: 'stitch span' },
  stretchPoints: { ru: 'растяжка нижней точки', en: 'stretch the points' },
  sujidate: { ru: 'sujidate', en: 'sujidate', ja: '筋立て上掛け千鳥かがり', ruCanon: 'судзидатэ' },
  support: { ru: 'опора', en: 'support' },
  tail: { ru: 'хвост', en: 'tail' },
  tamadome: { ru: 'без узла', en: 'no knot', ja: '玉止め' },
  tangent: { ru: 'касательный вход', en: 'tangent join' },
  tanjunTobun: { ru: 'простое деление', en: 'simple equal division (S-N)', ja: '単純等分' },
  tekobari: { ru: 'тэкобари', en: 'tekobari', ja: '手古針' },
  temari: { ru: 'темари', en: 'temari', ja: '手まり' },
  temariNeedle: { ru: 'игла для темари', en: 'temari needle', ja: '手まり針' },
  tent: { ru: 'шатёр', en: 'tent' },
  tip: { ru: 'кончик', en: 'tip' },
  tipCross: { ru: 'крест у кончика', en: 'tip cross' },
  toleranceClass: { ru: 'класс допуска', en: 'tolerance class' },
  topPoint: { ru: 'верхняя точка', en: 'top point' },
  tsumu: { ru: 'цуму', en: 'tsumu', ja: 'つむかがり' },
  uwagake: { ru: 'uwagake', en: 'uwagake', ja: '上掛け千鳥かがり', ruCanon: 'увагакэ тидори' },
  valence: { ru: 'валентность', en: 'valence' },
  weave: { ru: 'переплетение', en: 'weave' },
  wedge: { ru: 'клин', en: 'wedge' },
  wrap: { ru: 'намотка', en: 'wrap' },
  yaegiku: { ru: 'яэгику', en: 'yaegiku', ja: '八重菊' }
});

/** @type {Readonly<Record<string, keyof typeof TERM>>} */
export const TERM_ALIASES = Object.freeze({
  catch: 'pickup',
});

export function termRu(id) {
  const key = TERM_ALIASES[id] || id;
  const t = TERM[key];
  return t ? t.ru : id;
}
