// #5 lift mechanics — regenerate samples/lift/numbers.md from sim/src/mechanics.js at the current defaults
// (model/lift-spec.md §1.3–§1.7, §2, §7; v1.1 C.3: the tables are illustrations the code regenerates, acceptance is by
// formulas and limits). Run: node sim/tools/lift-numbers.mjs > samples/lift/numbers.md
import * as M from '../src/mechanics.js';
import { loadRecipe } from '../src/recipe.js';
import { computeAll } from '../src/layers.js';

const C = 240, R = C / (2 * Math.PI), w = 0.714, h = M.H_REF_MM;
const D = M.LIFT_DEFAULTS, T0 = D.T.value, k0 = D.k.value, B0 = D.B.value, kap = D.kappa.value;
const f = (x, d = 3) => (Number.isFinite(x) ? x.toFixed(d) : '∞');
const r = M.rise1({ R, T: T0, k: k0, B: B0, h });
const { wc, rhoC } = M.crest(w, h, r.tc);
const out = [];
const p = (s = '') => out.push(s);

p('# Lift at crossings — numbers (#5)');
p();
p(`Generated by \`node sim/tools/lift-numbers.mjs\` from \`sim/src/mechanics.js\` (model/lift-spec.md v1.1). Defaults: C ${C} mm (R ${f(R, 2)} mm), w ${w} mm, h ${h} mm, T ${T0} N, k ${k0} N/mm², B ${B0} N·mm², κ ${kap}. The tables are illustrations at these defaults (lift-spec v1.1 C.3): acceptance is by the formulas and limits in sim/test/mechanics.test.mjs, not by reprinted numbers.`);
p();
p('## Single crossing (§1.3, T8) and derived constants (§2)');
p();
p('| Quantity | Value | Formula |');
p('|---|---|---|');
const rows = [
  ['Δ₁ (single-crossing rise)', `${f(r.delta1)} mm = ${f(r.delta1 / w, 2)} w`, 'Δ₁ = 1.5·t_c(F) − h/2 − δ(F), fixed point'],
  ['F (force at the crossing)', `${f(r.F)} N`, 'F = 2T·σ'],
  ['t_c (compressed thickness)', `${f(r.tc)} mm = ${f(r.tc / w, 2)} w`, 't_c = 0.491 − 0.068·ln(0.244·F[gf])'],
  ['δ (dent of the lower thread)', `${f(r.dent, 4)} mm`, 'δ = F / (2√k·√(T + 2√(Bk)))'],
  ['d_low (lower axis drop)', `${f(r.dent + (h - r.tc) / 2)} mm`, 'd_low = δ + (h − t_c)/2'],
  ['σ (flight slope)', `${f(r.sigma, 4)} (θ ${f(Math.atan(r.sigma) * 180 / Math.PI, 1)}°)`, 'σ = x₀/R + √(s₀/R)'],
  ['x₀ (free flight)', `${f(r.x0)} mm`, 'x₀ = √(R(2Δ₁ − s₀)) − √(R s₀)'],
  ['a = √(2RΔ₁) (tent half-length)', `${f(r.a1, 2)} mm = ${f(r.a1 / w, 1)} w`, 'rigid limit'],
  ['s₀, λ_T, λ_B, ℓ_b', `${f(r.s0, 4)}, ${f(r.lamT)}, ${f(r.lamB)}, ${f(r.lb)} mm`, 's₀ = T/(kR), λ_T = √(T/k), λ_B = (4B/k)^¼, ℓ_b = √(B/T)'],
  ['Π (regime)', f(r.Pi, 2), 'Π = T/(2√(Bk)); > 1 — tension regime'],
  ['w_c, ρ_c (crest)', `${f(wc)}, ${f(rhoC)} mm`, 'w_c = w·h/t_c, ρ_c = (w_c/2)²/(t_c/2)'],
  ['ψ*', `${f(M.psiStar(r.sigma, rhoC, wc) * 180 / Math.PI, 1)}°`, 'ψ* = asin(2σρ_c/w_c)'],
  ['ΔL per crossing', `${f(M.extraLengthApex({ D: r.delta1, lp: 0, kc: 0, Ds: r.delta1, ss: r.sigma }, R, r.s0, r.lamT), 4)} mm (lower bound (4/3)Δ₁σ ${f(M.extraLength1(r.delta1, r.sigma), 4)})`, 'crest + flights + tails'],
];
for (const x of rows) p(`| ${x.join(' | ')} |`);
p();
p('## Δ₁(T, k), mm (§1.3)');
p();
const ks = [0.3, 1, 3, 10, Infinity], Ts = [0.5, 1, 2, 3];
p(`| T, N \\ k, N/mm² | ${ks.map((k) => (Number.isFinite(k) ? k : '∞ (rigid ball)')).join(' | ')} |`);
p(`|---|${ks.map(() => '---').join('|')}|`);
for (const T of Ts) p(`| ${T} | ${ks.map((k) => f(M.rise1({ R, T, k, B: B0, h }).delta1)).join(' | ')} |`);
p();
p('0.000 = the dent eats the whole rise (very soft wrap under a high tension; Δ₁ is clipped at 0).');
p();
p('## Crossing angle ψ (§1.5): plateau on the crest and tent half-length');
p();
const psis = [90, 60, 45, 30, 20, 15];
const aps = psis.map((d) => M.apexOf(r.delta1, d * Math.PI / 180, { R, s0: r.s0, rhoC, wc }));
p(`| ψ | ${psis.map((d) => `${d}°`).join(' | ')} |`);
p(`|---|${psis.map(() => '---').join('|')}|`);
p(`| ℓ_p, mm | ${aps.map((a) => f(a.lp)).join(' | ')} |`);
p(`| a = ℓ_p + x₀(Δ_s), mm (without the λ_T tail) | ${aps.map((a) => f(a.lp + a.x0s, 2)).join(' | ')} |`);
p(`| former display w/sin ψ, mm | ${psis.map((d) => f(w / Math.sin(d * Math.PI / 180), 2)).join(' | ')} |`);
p();
p('## Stack of m threads (§1.6, T9) — inside one contact patch');
p();
p('| m | Δ(m), mm | Δ/w | a = √(2RΔ), mm | Δ_cap(m), mm (rigid ceiling) |');
p('|---|---|---|---|---|');
for (const m of [1, 2, 3, 4]) { const Dm = M.stackRise(r.delta1, m, kap); p(`| ${m} | ${f(Dm)} | ${f(Dm / w, 2)} | ${f(Math.sqrt(2 * R * Dm), 1)} | ${f(M.capRise(m, r.tc, h))} |`); }
p();
p('The pure stack is the patch rule; on patterns the support rule (§1.6/§1.8 v1.1) places the upper thread on the loaded lower thread (sag and flight kink), so heights between patches stay well below Δ(m).');
p();
p('## Dent of the lower thread vs the wrap stiffness (§1.7), T = 1 N');
p();
const kd = [0.3, 1, 3, 10], rd = kd.map((k) => M.rise1({ R, T: T0, k, B: B0, h }));
p(`| k, N/mm² | ${kd.join(' | ')} |`);
p(`|---|${kd.map(() => '---').join('|')}|`);
p(`| δ, mm | ${rd.map((x) => f(x.dent)).join(' | ')} |`);
p(`| δ/Δ₁ | ${rd.map((x) => f(x.dent / x.delta1, 2)).join(' | ')} |`);
p(`| d_low, mm | ${rd.map((x) => f(x.dent + (h - x.tc) / 2)).join(' | ')} |`);
p();
p('## Whole patterns, liftMode ideal (support rule, Fable Q5)');
p();
p('Δ_c statistics over apices with Δ_c > 0 (as K19 prints them).');
p();
p('| Config | apices | m_max | Δ_c median / p95 / max, mm | lifted − axis | supports (plateau / bridge / flight / ground) |');
p('|---|---|---|---|---|---|');
const recipe = await loadRecipe();
const cfgs = [['S8 uwagake, bow λ 0.32, m 0.5 (site view)', { topRule: 'uwagake', m_mm: 0.5, shoulderForm: 'bow', bowLambda: 0.32 }],
  ['fan, bow λ 0.32, m 0.5', { topRule: 'fan', m_mm: 0.5, shoulderForm: 'bow', bowLambda: 0.32 }],
  ['uwagake, geodesic, m 0.5 (engine default)', {}],
  ['stress: uwagake, bow λ 0.6, m 1', { topRule: 'uwagake', m_mm: 1, shoulderForm: 'bow', bowLambda: 0.6 }]];
for (const [name, raw] of cfgs) {
  const A = computeAll(recipe, { ...raw, liftMode: 'ideal' }), X = A.mechanics, d = X.crossings.map((c) => c.delta).filter((v) => v > 0).sort((a, b) => a - b);
  const q = (t) => d[Math.min(d.length - 1, Math.floor(t * d.length))], sc = X.consts.supportCounts || {}, Tt = X.lengths.total;
  p(`| ${name} | ${X.nApex} | ${X.mMax} | ${f(q(0.5))} / ${f(q(0.95))} / ${f(d[d.length - 1])} | +${f(100 * (Tt.lifted - Tt.axis) / Tt.axis, 2)} % | ${['plateau', 'bridge', 'flight', 'ground'].map((k) => sc[k] ?? 0).join(' / ')} |`);
}
p();
p('## Formulas (§7)');
p();
for (const s of [
  's₀ = T/(kR); λ_T = √(T/k); λ_B = (4B/k)^¼; ℓ_b = √(B/T); Π = T/(2√(Bk)).',
  't_c(F) = 0.491 − 0.068·ln(0.244·F[gf]) mm (pearl #5; scaled by h/0.464 for another laid height, (c)).',
  'δ = F/(2√k·√(T + 2√(Bk))); d_low = δ + (h − t_c)/2.',
  'Δ₁ = 1.5·t_c − h/2 − δ; F = 2T·σ; σ = x₀/R + √(s₀/R); x₀ = √(R(2Δ₁ − s₀)) − √(R s₀); a ≈ √(2RΔ₁).',
  'u(x) = Δ₁ − σ|x| + x²/2R (|x| ≤ x₀), s₀·e^{−(|x|−x₀)/λ_T} beyond; rigid limit Δ₁(1 − |x|/a)².',
  'Bridge: u = Δ_i + (Δ_j − Δ_i)·x/L − x(L − x)/2R if ≥ 0; condition L ≤ √(8RΔ).',
  'ΔL₁ ≥ (4/3)·Δ₁·σ (full: crest + flights + tails); Δ(m) = Δ₁(1 + κ(m − 1)); Δ_cap(m) = (m + ½)·t_c − h/2.',
  'Support (v1.1): z_sup = u_L,loaded(y_c) − sag, sag = 2σ_U·ab/(a + b); flight kink u_L(x) → max(0, u_L(x) − 2σ_U·(x − y)); Δ_c = z_sup + Δ₁(F_c), F_c = 2Tσ_U; κ only inside the contact patch.',
  'K18: Δ_c − z_sup ≤ 1.5·t_c(F_c) − h/2; K19: max Δ_c printed, warn > 1.2 mm.',
  'ρ_c = (w_c/2)²/(t_c/2), w_c = w·h/t_c; ℓ_p = min(σρ_c/sin²ψ, w_c/(2 sin ψ), max(w_c/2, c.lenMm/2)); ψ* = asin(2σρ_c/w_c).',
]) p(`- ${s}`);
console.log(out.join('\n'));
